version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: nuget
    directory: /backend
    schedule:
      interval: weekly
      day: monday
    groups:
      backend:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /frontend/Planora.Web.User
    schedule:
      interval: weekly
      day: monday
    groups:
      user-web:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /frontend/Planora.Web.Admin
    schedule:
      interval: weekly
      day: monday
    groups:
      admin-web:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      root-containers:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
      day: monday
    groups:
      backend-container:
        patterns: ["*"]
