@Planora.Api_HostAddress = http://localhost:8080

GET {{Planora.Api_HostAddress}}/
Accept: application/json

###

GET {{Planora.Api_HostAddress}}/health/live

###

POST {{Planora.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "owner@example.com",
  "password": "ChangeMe!123",
  "displayName": "Project Owner",
  "deviceInfo": "local.http"
}
